#!/usr/bin/env python
# calsync.py
# rsync my calibre library to the NAS

import os
import logging
from datetime import datetime

logging.disable(logging.CRITICAL)
logging.basicConfig(level=logging.DEBUG, format='%(levelname)s: %(asctime)s %(message)s', datefmt="%Y-%m-%d %H:%M:%S")
logging.debug('=======================')
logging.debug('=== start of program ===')

print("\n\n>>> Starting Boardgame sync...\n")

startdir = os.getcwd()
print(">>> Moving to: /Volumes/JetDrive/Boardgames/_GameRules-Library/ ...\n")
os.chdir("/Volumes/JetDrive/Boardgames/_GameRules-Library/")

bashCommand = "find /Volumes/JetDrive/Boardgames/_GameRules-Library/ -name '.DS_Store' -print -delete"
print(">>> Removing .DS_Store files...\n")
os.system(bashCommand)

bashCommand = "find /Volumes/JetDrive/Boardgames/_GameRules-Library/ -type d -empty -print -delete"
print(">>> Removing empty directories...\n")
os.system(bashCommand)

bashCommand = "rsync -h -r -t -x -v --progress --delete --size-only --exclude=.DS_Store /Volumes/JetDrive/Boardgames/_GameRules-Library/ dave@192.168.1.29:boardgame-server"
print(">>> Copying files to 192.168.1.29:boardgame-server ...\n")
#os.system(bashCommand)

bashCommand = "rsync -h -r -t -x -v --progress --delete --size-only --exclude=.DS_Store /Volumes/JetDrive/Boardgames/_GameRules-Library/ dave@192.168.1.42:boardgame-server"
print("")
print(">>> Copying files to 192.168.1.42:boardgame-server ...\n")
os.system(bashCommand)

print("")
print(">>> Returning to original directory...\n")
os.chdir(startdir)

print(">>>", datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
print("\n>>> All done!\n")
