#!/usr/bin/env python
# calimport.py
# Runs through a directory (and sub-dirs) and eliminates unwanted ebook formats
# and imports the remainder to calibre.
# "Eliminates unwanted formats" means keep the most preferred format and
# delete the rest.  Formats are preferred in the order
# epub, azw3, azw, mobi, ... pdf
# This should also unpack archives but as they're in varying formats I'm not
# sure how to do that from CLI - hmmm, the open command works

import os
import logging

logging.disable(logging.CRITICAL)
logging.basicConfig(level=logging.DEBUG, format='%(levelname)s: %(asctime)s %(message)s', datefmt="%Y-%m-%d %H:%M:%S")
logging.debug('=======================')
logging.debug('=== start of program ===')

startdir = os.getcwd()
logging.debug('startdir = ' + startdir)

#in_dir = os.path.expanduser("~/Dropbox/_calibre-auto-add")
in_dir = os.path.expanduser("~/Downloads/cal-import")
logging.debug('in_dir = ' + in_dir)
os.chdir(in_dir)    # this should probably try in case there's an error

# need to get directory and then unpack any archives
# bash open works for rar and zip but there's some funkiness
#	as it uses the GUI unarchiver
# bashCommand = "open ChildrenMoon3.rar"
# logging.debug('bashCommand = ' + bashCommand)
# os.system(bashCommand)

quit()
#=======================
# the rest of this is the calupdate script that I used as a starter...

bashCommand = "wget -O calibre-latest.dmg -N http://status.calibre-ebook.com/dist/osx32"
logging.debug('bashCommand = ' + bashCommand)
os.system(bashCommand)

bashCommand = "open " + in_dir + "/calibre-latest.dmg"
logging.debug('bashCommand = ' + bashCommand)
os.system(bashCommand)

os.chdir(startdir)

logging.debug('=== end of program ===')
logging.debug('=======================')
