#!/usr/bin/env python
# calsync
# rsync my calibre library to an iMac and Mac Mini that serve up the files
# ToDo: Add options to backup to one or both libraries (or to an arbitrary address?)
# ToDo: Add option to reverse direction and copy from the remote to the local
# ToDo: If you add options add usage messages
# ToDo: undupe the copy commands by moving them into a function

# import libraries
import os
import logging
from datetime import datetime

# setup debug logging (and disable by default)
logging.disable(logging.CRITICAL)
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')
logging.debug('start of program')


rsync = "rsync -h -r -t -x -v --delete --size-only --exclude=.DS_Store "
#srcdir = '/Users/dave/Books/Calibre-MBP'
srcdir = '/Volumes/JetDrive/Calibre-JD'
print("\n\n>>> Starting Calibre sync...\n")

# save the current directory and then change to the Calibre directory
print(">>> Moving to: " + srcdir + " ...\n")
startdir = os.getcwd()
os.chdir(srcdir+"/")

# remove all those stinking .DS_Store things that macOS leaves all over
bashCommand = "find "+ srcdir + " -name '.DS_Store' -print -delete"
print(">>> Removing .DS_Store files...")
print(bashCommand)
print("")
os.system(bashCommand)

# remove any empty directory left behind from working in Calibre
bashCommand = "find "+ srcdir + " -type d -empty -print -delete"
print(">>> Removing empty directories...")
print(bashCommand)
print("")
#os.system(bashCommand)

#=======================
# copy files to .29 (iMac)
tgtdir = "dave@192.168.1.29:calibre-server"
#bashCommand = "rsync -h -r -t -x -v --delete --size-only --exclude=.DS_Store /Users/dave/Books/Calibre-MBP/ dave@192.168.1.29:calibre-server"
bashCommand = rsync + srcdir + "/ " + tgtdir
print(">>> Copying files to " + tgtdir + " ...")
print(bashCommand)
os.system(bashCommand)

# copy files to .42 (Mini)
tgtdir = "dave@192.168.1.42:calibre-server"
#bashCommand = "rsync -h -r -t -x -v --delete --size-only --exclude=.DS_Store /Users/dave/Books/Calibre-MBP/ dave@192.168.1.42:calibre-server"
bashCommand = rsync + srcdir + "/ " + tgtdir
print("")
print(">>> Copying files to " + tgtdir + " ...")
print(bashCommand)
os.system(bashCommand)

# # copy files to JetDrive
# tgtdir = "/Volumes/JetDrive/Calibre-JD/"
# #bashCommand = "rsync -h -r -t -x -v --delete --size-only --exclude=.DS_Store /Users/dave/Books/Calibre-MBP/ dave@192.168.1.42:calibre-server"
# bashCommand = rsync + srcdir + "/ " + tgtdir
# print("")
# print(">>> Copying files to " + tgtdir + " ...")
# print(bashCommand)
# os.system(bashCommand)

#=======================
# pseudo code for a restore option
# RESTORE - Reverse the Stream - Server back to MBP
# NOTE the / on the source but not the destination
# issue ARE YOU SURE? warning
# do it once with --dry-run
#rsync --dry-run -h -r -t -x -v --size-only --exclude=.DS_Store dave@192.168.1.42:calibre-server/ /Users/dave/Books/Calibre-MBP
# issue ARE YOU REALLY SURE YOU WANT TO WIPE OUT THE LOCAL CALIBRE LIBRARY? warning
# do it for reals
#rsync -h -r -t -x -v --size-only --exclude=.DS_Store dave@192.168.1.42:calibre-server/ /Users/dave/Books/Calibre-MBP
#=======================

# return to the original directory
print("")
print(">>> Returning to original directory...\n")
os.chdir(startdir)

print(">>>", datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
print(">>> All done!\n")
