#!/usr/bin/env python
# calsearch
# Search calibre

import subprocess
import json
import os

result = {"items": []}

rawData = subprocess.check_output(['/Applications/calibre.app/Contents/MacOS/calibredb', 'list', '-f', 'title, cover, formats', '--for-machine'])
rawData = rawData.decode('unicode-escape')
jsonData = json.loads(rawData)


for item in jsonData:
    temp = {}
    temp["type"] = "file"
    _, file_extension = os.path.splitext(item["formats"][0])
    temp["title"] = "[" + file_extension[1:].upper() + "] " + item["title"]
    # cover = item["cover"]
    # itemId = item["id"]
    temp["subtitle"] = item["formats"][0]
    temp["arg"] = item["formats"][0]
    result['items'].append(temp)

print(json.dumps(result))
