#!/usr/local/bin/python
# calsync.py
# rsync my calibre library to the NAS
import os

print "\n\nStarting Calibre sync...\n"

print "Moving to: /Users/dave/Books/Calibre-MBP ...\n"
startdir = os.getcwd()
os.chdir("/Users/dave/Books/Calibre-MBP/")

print "Removing .DS_Store files...\n"
#find /Users/dave/Books/Calibre-MBP -name ".DS_Store" -delete
bashCommand = "find /Users/dave/Books/Calibre-MBP -name '.DS_Store' -print -delete"
os.system(bashCommand)

print "Removing empty directories...\n"
bashCommand = "find /Users/dave/Books/Calibre-MBP -type d -empty -print -delete"
os.system(bashCommand)

# !!! Change this so that it looks for /Volumes/Calibre/Calibre-NAS and if not found unmount Calibre 
# !!! This is to fix cases where OSX goes to sleep with the NAS mounted and then 
# !!!    can't get to it when it wakes up
#print "Unmount /Volumes/Calibre...\n"
#bashCommand = "umount /Volumes/Calibre"
#os.system(bashCommand)

#print "Mounting smb://qnap-nas/Books...\n"
#bashCommand = "automator ~/bin/Mount_Calibre.workflow"
#os.system(bashCommand)

#print "Copying files to /Volumes/Books/Calibre-NAS ...\n"
print "Copying files to 192.168.1.15:calibre-server ...\n"
#bashCommand = "rsync -h -r -t -x -v --progress --delete --size-only --exclude=.DS_Store /Users/dave/Books/Calibre-MBP/ /Volumes/Books/Calibre-NAS"
#bashCommand = "rsync -h -r -t -x -v --info=progress2 --delete --size-only --exclude=.DS_Store /Users/dave/Books/Calibre-MBP/ /Volumes/Books/Calibre-NAS"
bashCommand = "rsync -h -r -t -x -v --info=progress2 --delete --size-only --exclude=.DS_Store /Users/dave/Books/Calibre-MBP/ dave@192.168.1.15:calibre-server"
os.system(bashCommand)

#print "Unmount /Volumes/Calibre...\n"
#bashCommand = "umount /Volumes/Calibre"
#os.system(bashCommand)

print "Returning to original directory...\n"
print os.system('date')
os.chdir(startdir)


print "\nAll done!\n"
