#!/usr/bin/env python
# calupdate.py
# download the latest version of calibre
import os
import logging

logging.disable(logging.CRITICAL)
logging.basicConfig(level=logging.DEBUG, format='%(levelname)s: %(asctime)s %(message)s', datefmt="%Y-%m-%d %H:%M:%S")
logging.debug('=======================')
logging.debug('=== start of program ===')


startdir = os.getcwd()
logging.debug('startdir = ' + startdir)

dl_dir = os.path.expanduser("~/Downloads")
logging.debug('dl_dir = ' + dl_dir)
os.chdir(dl_dir)

#bashCommand = "wget -O calibre-latest.dmg -N http://status.calibre-ebook.com/dist/osx32"
bashCommand = "wget -O calibre-latest.dmg -N http://status.calibre-ebook.com/dist/osx32"
logging.debug('bashCommand = ' + bashCommand)
os.system(bashCommand)

bashCommand = "open " + dl_dir + "/calibre-latest.dmg"
logging.debug('bashCommand = ' + bashCommand)
os.system(bashCommand)

os.chdir(startdir)

logging.debug('=== end of program ===')
logging.debug('=======================')
