#!/usr/bin/env python
# 2015-09-30/DN: Script to commafy a single number.
# 2016-08-31/DN: Added logging (cause I just learned about it) and
#	better error handling

import sys
import logging

logging.disable(logging.CRITICAL)
logging.basicConfig(level=logging.DEBUG, format='%(levelname)s: %(asctime)s %(message)s', datefmt="%Y-%m-%d %H:%M:%S")
logging.debug('=======================')
logging.debug('=== start of program ===')

# converts to int first, if that fails it tries float, if that fails it bails out
try:
	sys.argv[1]
except:
	print ("Usage: commify [ integer | float ]\n")
	quit()

try:
	logging.debug('convert to integer')
	input = int(sys.argv[1])
	output = format(input, ',')
except ValueError:
	try:
		logging.debug('convert to float')
		input = float(sys.argv[1])
		output = format(input, ',')
	except:
		logging.debug('not a number')
		output = "{a} is Not a Number".format(a=sys.argv[1])

print (output)
logging.debug('=== end of program ===')
logging.debug('=======================')
