#!/usr/bin/expect
#
# Set the date.
set date [timestamp -format %Y-%m-%d_%H%M%S]
set DEVICE 172.16.16.1

#ssh to the device as user
spawn ssh $DEVICE -l user

#supply the Password at the prompt
expect "assword:"
send "password\n"

#go to enable mode
expect ".*>"
send "en\n"
expect "assword:"
send "password\n"

#Tell the device to turn off paging
expect ".*#"
send "term pager 0\n"

expect ".*#"
send "more system:running-config\n"

# output to file with timestamp 
#-noappend will create a new file if one already exists
log_file -noappend ~/scratch/${date}_getconf.log

#Exit out of the network device
expect ".*#"
send "exit\n"

# stop output to file 
log_file 
