#!/usr/bin/expect
#
# Set the date.
set date [timestamp -format %Y-%m-%d_%H%M%S]
#set DEVICE 10.10.100.1
set DEVICE 172.16.10.1
#set DEVICE 50.202.126.170
#set DEVICE 10.10.106.229

#ssh to the device as user
spawn ssh $DEVICE -l gozer

#supply the Password at the prompt
expect "assword:"
send "Changeme!\n"

#go to enable mode
expect "pancetta>"
send "en\n"
expect "assword:"
send "bagre#sonata#spass\n"

#Tell the device to turn off paging
expect "pancetta#"
send "term pager 0\n"

expect "pancetta#"
send "more system:running-config\n"

# output to file with timestamp 
#-noappend will create a new file if one already exists
log_file -noappend ~/scratch/${date}_getconf.log

#Exit out of the network device
expect "pancetta#"
send "exit\n"

# stop output to file 
log_file 
