#!/usr/bin/env python

from pync import Notifier

Notifier.notify('WifiWatch')
#Notifier.notify('WifiWatch', title='Python')
#Notifier.notify('WifiWatch', group=os.getpid())
#Notifier.notify('WifiWatch', activate='com.apple.Safari')
#Notifier.notify('WifiWatch', open='http://github.com/')
#Notifier.notify('WifiWatch', execute='say "OMG"')

#Notifier.remove(os.getpid())

#Notifier.list(os.getpid())
