#!/bin/bash
# 2014-08-18/DN: This was originally a quick copy of all the files listed in an 
# M3U into a directory. It's now an bash example file.

InFile=$1
TgtDir=$2

if [[ "$InFile" == "" || $TgtDir == "" ]]; then
  echo
  echo Usage: whilefile \$1 \$2 where:
  echo \$1 is a File name
  echo \$2 is a Directory
  echo
else            
  while read Line; do
    cp "$Line" "$TgtDir"
  done <$InFile
fi

# example for loop
# for i in {1..5}; do COMMAND-HERE; done
# for((i=1;i<=10;i+=2)); do echo "Welcome $i times"; done

